services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: publish
      PORT: 8080
      BLUEPRINT_DB_URL: ${BLUEPRINT_DB_URL}
    volumes:
      - sqlite_bp:/app/db
      - ../data-services/dist:/app/data-services
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    restart: unless-stopped
    ports:
      - 5173:5173
    environment:
      - API_TARGET=http://app:8080
    depends_on:
      - app
volumes:
  sqlite_bp:
